@startuml(id=Containers)
title Hotel Reservation System - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<11>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam rectangle<<22>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam rectangle<<27>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<31>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<10>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
rectangle "==Customer\n<size:10>[Person]</size>\n\nAn online booking customer" <<1>> as 1
rectangle "==Management\n<size:10>[Person]</size>\n\nStore all hotel information about customer, room, booking date, etc" <<31>> as 31
rectangle "==Notification System\n<size:10>[Software System]</size>\n\nSend SMS to customers: successful booking, room problems, etc" <<27>> as 27
package "Hotel Reservation System\n[Software System]" {
  rectangle "==Api Application\n<size:10>[Container: PHP and Laravel]</size>\n\nProvides Hotel reservation functionality via a JSON/HTTPS API" <<11>> as 11
  rectangle "==Database\n<size:10>[Container: SQL Server]</size>\n\nStore customer information, booking date and time, room information,etc" <<22>> as 22
  rectangle "==Single-Page Application\n<size:10>[Container: PHP and Laravel]</size>\n\nProvides all Hotel reservation functionality via their browser" <<10>> as 10
  rectangle "==Web Application\n<size:10>[Container: PHP and Laravel]</size>\n\nDelivers hotel infomation and the Hotel reservation single page application" <<3>> as 3
}
11 .[#707070,thickness=2].> 22 : "Reads from and writes to\n<size:8>[JDBC]</size>"
11 .[#707070,thickness=2].> 27 : "Sends SMS using"
1 .[#707070,thickness=2].> 10 : "View room information and make a reservation"
1 .[#707070,thickness=2].> 3 : "Visits phuonganhhotel.com using\n<size:8>[Https]</size>"
31 .[#707070,thickness=2].> 3 : "retrieves statistics from"
27 .[#707070,thickness=2].> 1 : "Sends notification to"
10 .[#707070,thickness=2].> 11 : "Makes API calls to\n<size:8>[Json/Https]</size>"
3 .[#707070,thickness=2].> 31 : "retrieves statistics from"
3 .[#707070,thickness=2].> 10 : "Delivers to the customer 's web browser"
@enduml